-- 2026-09-23 (applied directly on production via Supabase MCP; recorded here for history)

-- 1) The app selects `id, wrong_count` from key_wrong_answers, but the table had
--    no `id` column -> GET 400 "column key_wrong_answers.id does not exist" and
--    wrong answers were not synced. Additive fix, no app change needed.
alter table public.key_wrong_answers add column if not exists id bigint generated by default as identity;

-- 2) students / license_keys had RLS disabled: anyone with the public anon key
--    could update/delete/truncate them (e.g. deactivate every key, wipe students).
--    Student app never touches students and only SELECTs license_keys;
--    admin.html signs in as admin@skl.com.tw; auto-register-student uses service_role.
alter table public.students enable row level security;
create policy students_admin_all on public.students
  for all to authenticated
  using ((auth.jwt() ->> 'email') = 'admin@skl.com.tw')
  with check ((auth.jwt() ->> 'email') = 'admin@skl.com.tw');

alter table public.license_keys enable row level security;
create policy license_keys_read on public.license_keys
  for select to anon, authenticated using (true);
create policy license_keys_admin_write on public.license_keys
  for all to authenticated
  using ((auth.jwt() ->> 'email') = 'admin@skl.com.tw')
  with check ((auth.jwt() ->> 'email') = 'admin@skl.com.tw');

revoke truncate on public.students, public.license_keys from anon, authenticated;

-- used_count bump must keep working for the anon student app under RLS
create or replace function public.increment_key_used_count(k_id uuid)
returns void language sql security definer set search_path = public as $$
  update public.license_keys set used_count = used_count + 1 where id = k_id;
$$;

-- Rollback (if ever needed):
--   alter table public.students disable row level security;
--   alter table public.license_keys disable row level security;
